# python version variable

jobs:
  - job: black
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.8'
      displayName: '3.8'
    - script: |
        python -m pip install --upgrade pip
        pip install -r requirements-dev.txt
      displayName: 'Install dependencies'
    - script: |
        python -m black --check ds_toolbox/
      displayName: 'Black formatting check..'

  - job: pytest
    pool:
      vmImage: 'ubuntu-latest'
    strategy:
      matrix:
        LinuxPackageInstallPython37:
          python.version: '3.7'
        LinuxPackageInstallPython38:
          python.version: '3.8'
        LinuxPackageInstallPython39:
          python.version: '3.9' 
    steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '$(python.version)'
      displayName: '$(python.version)'
    - script: |
        python -m pip install --upgrade pip
        pip install -r requirements-dev.txt
        pip install -r requirements.txt
      displayName: 'Installing dependencies..'
    - script: |
        python -m pytest ds_toolbox
      displayName: 'pytest'
