# This will run the pipeline whenever anything new is committed to master
trigger:
  - main

jobs:
  - job: build_publish_docs
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.8'
      displayName: 'Use Python 3.8'

    - script: |
        pip install -r requirements-dev.txt
        pip install -r requirements.txt
        pip install -e .
    - script: |
        make html
      workingDirectory: docs/
      displayName: Build docs
    - task: AWSShellScript@1
      inputs:
        awsCredentials: "AWS ds_toolbox"
        failOnStandardError: true
        regionName: eu-central-1
        scriptType: "inline"
        inlineScript: "aws s3 sync docs/_build/html/ s3://dfds-dstoolbox-docs/"
      displayName: Sync with s3

  - job: build_publish_package
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.8'
      displayName: 'Use Python 3.8'

    - script: |
        pip install wheel
        pip install twine
      displayName: 'install twine'

    - task: TwineAuthenticate@1
      displayName: 'Twine Authenticate'
      inputs:
        artifactFeed: smartdata

    - script: |
        python setup.py bdist_wheel
      displayName: 'build'
      
    - script: |
        python -m twine upload -r smartdata --config-file $(PYPIRC_PATH) dist/*.whl
      displayName: 'upload'