name: pytester-cov workflow

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
    - main

jobs:
  coverage:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install Poetry
      uses: snok/install-poetry@v1
      with:
        version: 1.1.14
        virtualenvs-create: false

    - name: Install dependencies
      run: |
        poetry install --no-interaction

    - name: Build coverage file
      run: |
        poetry run pytest --cache-clear --cov=dfds_ds_toolbox test/ > pytest-coverage.txt

    - name: pytest-coverage-commentator
      uses: coroo/pytest-coverage-commentator@v1.0.2
      with:
        pytest-coverage: pytest-coverage.txt